apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::911224332456:role/default-eks-node-group-20260210155908581600000003
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::911224332456:user/bedrock-dev-view
      username: bedrock-dev-view
      groups:
        - view-only
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
