apiVersion: v1
kind: Service
metadata:
  name: retail-store-ui-ci
  namespace: retail-app
spec:
  selector:
    app: retail-store-ui-ci
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
